server:
  port: 8007
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: edu-order-boot
  shardingsphere:
    datasource:
      name: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.79.129:3307/edu_order?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
    sharding:
      tables:
        user_course_order:    #指定user_course_order表的数据分布情况，配置数据结点
          actualDataNodes: ds0.user_course_order_$->{0..2}
          tableStrategy:
            inline:  #指定user_course_order表的分片策略，包括分片键和分片算法
              shardingColumn: id
              algorithmExpression: user_course_order_$->{id % 3}
          keyGenerator:
            type: SNOWFLAKE
            column: id #指定主键
    props:
      sql:
        show: true
  rabbitmq:
    host: 192.168.79.129
    port: 5672
    username: root
    password: 123456
    virtual-host: lagou
    queue: order_queue
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

