server:
  # 服务端口号
  port: 8002
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: edu-user-boot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.79.129:3307/edu_user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.79.129
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
